// <auto-generated />
using System;
using IEnablers.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IEnablers.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20210114125140_SP_GetApoointmentDataByID")]
    partial class SP_GetApoointmentDataByID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("IEnablers.Models.Appointment", b =>
                {
                    b.Property<int>("Appointment_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Appointment_Date_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Appointment_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PATIENT_RELATIONSHIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patient_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Visit_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Appointment_ID");

                    b.ToTable("appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
